obstacle_range: 5.0
raytrace_range: 6.0
footprint: [[0.305, 0.245], [0.305, -0.245], [-0.305, -0.245], [-0.305, 0.245]]
inflation_radius: 0.55
cost_scaling_factor: 10.0
transform_tolerance: 0.5
observation_sources: scan
scan:
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true

map_type: costmap
