global_costmap:
  global_frame: map
  robot_base_frame: ebot_base
  update_frequency: 4.0 #before: 5.0
  publish_frequency: 2.0 #before 0.5
  static_map: true
  transform_tolerance: 0.5
  cost_scaling_factor: 20.0
  inflation_radius: 2
